name: capstone_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - transformers
  - accelerate
  - pytest
  - reportlab
  - pypdf
  - flask
  - flask-sqlalchemy
  - sphinx